name = "rongen"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["rongen"]

[[depends-on]]
openglada = "~0.9.0"
openglada_text = "~0.9.0"
openglada_images = "~0.9.0"

[[depends-on]]
openglada_glfw = "~0.9.0"

[[depends-on]]
imgui = "*"

[[pins]]
openglada = { path='vendor/openglada' }
imgui = { path='vendor/ImGui-Ada' }

[environment.'case(distribution)'.homebrew]
HOMEBREW_PREFIX.set = "/opt/homebrew"

[[depends-on]]
gid = "^9.0.0"
